import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { useAuth } from "../src/components/authGurad/AuthContext";
import Image from "next/image";
import AuthLogo from "../src/layouts/logo/AuthLogo";
import LeftBg from "../src/assets/images/bg/login-bgleft.svg";
import RightBg from "../src/assets/images/bg/login-bg-right.svg";
import Head from "next/head";
import {
  Container,
  Row,
  Col,
  Button,
  Form,
  Card,
  CardBody,
  FormGroup,
  Label,
  Input,
  Alert,
} from "reactstrap";

export default function Home() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(null);
  const router = useRouter();
  const { signInWithEmailAndPassword } = useAuth();

  const onSubmit = (event) => {
    setError(null);
    signInWithEmailAndPassword(email, password)
      .then((authUser) => {
        console.log("Success. The user is created in firebase");
        router.push("/starter");
      })
      .catch((error) => {
        setError(error.message);
      });
    event.preventDefault();
  };

  return (
    <div>
      <Head>
        <title>Monster Firebase Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="loginBox">
        <div className="position-absolute start-0 bottom-0">
          <Image src={LeftBg} alt="left" />
        </div>
        <div className="position-absolute end-0 top">
          <Image src={RightBg} alt="right" />
        </div>
        {/***Sales & Feed***/}
        <Container fluid className="h-100">
          <Row className="justify-content-center align-items-center h-100">
            <Col lg="12" className="loginContainer">
              <AuthLogo />
              <Card>
                <CardBody className="p-4 m-1">
                  <h4 className="mb-0 fw-bold">Login with Firebase</h4>
                  <small className="pb-4 d-block">
                    Do not have an account? <Link href="/signup">Sign Up</Link>
                  </small>
                  <Form onSubmit={onSubmit}>
                    {error && <Alert color="danger">{error}</Alert>}
                    <FormGroup row>
                      <Label for="loginEmail" sm={12}>
                        Email
                      </Label>
                      <Col sm={12}>
                        <Input
                          type="email"
                          value={email}
                          onChange={(event) => setEmail(event.target.value)}
                          name="email"
                          id="loginEmail"
                          placeholder="Email"
                        />
                      </Col>
                    </FormGroup>
                    <FormGroup row>
                      <Label for="loginPassword" sm={12}>
                        Password
                      </Label>
                      <Col sm={12}>
                        <Input
                          type="password"
                          name="password"
                          value={password}
                          onChange={(event) => setPassword(event.target.value)}
                          id="loginPassword"
                          placeholder="Password"
                        />
                      </Col>
                    </FormGroup>
                    <FormGroup row>
                      <Col>
                        <Button color="primary">Login</Button>
                      </Col>
                    </FormGroup>
                  </Form>
                </CardBody>
              </Card>
              <Alert color="success">Email: demo@demo.com , PWD: demo123</Alert>
            </Col>
          </Row>
        </Container>
      </div>
    </div>
  );
}

Home.layout = "Blank";
