import Head from "next/head";
import { Col, Row } from "reactstrap";
import DashCard from "../src/components/dashboardCards/DashCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ample Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="12">
            <DashCard
              title="Start Your Project"
              subtitle="you can use this starterkit for your app"
            />
          </Col>
        </Row>
      </div>
    </div>
  );
}
